# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_epanet2', [dirname(__file__)])
        except ImportError:
            import _epanet2
            return _epanet2
        if fp is not None:
            try:
                _mod = imp.load_module('_epanet2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _epanet2 = swig_import_helper()
    del swig_import_helper
else:
    import _epanet2
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_epanet2.EN_ELEVATION_swigconstant(_epanet2)
EN_ELEVATION = _epanet2.EN_ELEVATION

_epanet2.EN_BASEDEMAND_swigconstant(_epanet2)
EN_BASEDEMAND = _epanet2.EN_BASEDEMAND

_epanet2.EN_PATTERN_swigconstant(_epanet2)
EN_PATTERN = _epanet2.EN_PATTERN

_epanet2.EN_EMITTER_swigconstant(_epanet2)
EN_EMITTER = _epanet2.EN_EMITTER

_epanet2.EN_INITQUAL_swigconstant(_epanet2)
EN_INITQUAL = _epanet2.EN_INITQUAL

_epanet2.EN_SOURCEQUAL_swigconstant(_epanet2)
EN_SOURCEQUAL = _epanet2.EN_SOURCEQUAL

_epanet2.EN_SOURCEPAT_swigconstant(_epanet2)
EN_SOURCEPAT = _epanet2.EN_SOURCEPAT

_epanet2.EN_SOURCETYPE_swigconstant(_epanet2)
EN_SOURCETYPE = _epanet2.EN_SOURCETYPE

_epanet2.EN_TANKLEVEL_swigconstant(_epanet2)
EN_TANKLEVEL = _epanet2.EN_TANKLEVEL

_epanet2.EN_DEMAND_swigconstant(_epanet2)
EN_DEMAND = _epanet2.EN_DEMAND

_epanet2.EN_HEAD_swigconstant(_epanet2)
EN_HEAD = _epanet2.EN_HEAD

_epanet2.EN_PRESSURE_swigconstant(_epanet2)
EN_PRESSURE = _epanet2.EN_PRESSURE

_epanet2.EN_QUALITY_swigconstant(_epanet2)
EN_QUALITY = _epanet2.EN_QUALITY

_epanet2.EN_SOURCEMASS_swigconstant(_epanet2)
EN_SOURCEMASS = _epanet2.EN_SOURCEMASS

_epanet2.EN_INITVOLUME_swigconstant(_epanet2)
EN_INITVOLUME = _epanet2.EN_INITVOLUME

_epanet2.EN_MIXMODEL_swigconstant(_epanet2)
EN_MIXMODEL = _epanet2.EN_MIXMODEL

_epanet2.EN_MIXZONEVOL_swigconstant(_epanet2)
EN_MIXZONEVOL = _epanet2.EN_MIXZONEVOL

_epanet2.EN_TANKDIAM_swigconstant(_epanet2)
EN_TANKDIAM = _epanet2.EN_TANKDIAM

_epanet2.EN_MINVOLUME_swigconstant(_epanet2)
EN_MINVOLUME = _epanet2.EN_MINVOLUME

_epanet2.EN_VOLCURVE_swigconstant(_epanet2)
EN_VOLCURVE = _epanet2.EN_VOLCURVE

_epanet2.EN_MINLEVEL_swigconstant(_epanet2)
EN_MINLEVEL = _epanet2.EN_MINLEVEL

_epanet2.EN_MAXLEVEL_swigconstant(_epanet2)
EN_MAXLEVEL = _epanet2.EN_MAXLEVEL

_epanet2.EN_MIXFRACTION_swigconstant(_epanet2)
EN_MIXFRACTION = _epanet2.EN_MIXFRACTION

_epanet2.EN_TANK_KBULK_swigconstant(_epanet2)
EN_TANK_KBULK = _epanet2.EN_TANK_KBULK

_epanet2.EN_DIAMETER_swigconstant(_epanet2)
EN_DIAMETER = _epanet2.EN_DIAMETER

_epanet2.EN_LENGTH_swigconstant(_epanet2)
EN_LENGTH = _epanet2.EN_LENGTH

_epanet2.EN_ROUGHNESS_swigconstant(_epanet2)
EN_ROUGHNESS = _epanet2.EN_ROUGHNESS

_epanet2.EN_MINORLOSS_swigconstant(_epanet2)
EN_MINORLOSS = _epanet2.EN_MINORLOSS

_epanet2.EN_INITSTATUS_swigconstant(_epanet2)
EN_INITSTATUS = _epanet2.EN_INITSTATUS

_epanet2.EN_INITSETTING_swigconstant(_epanet2)
EN_INITSETTING = _epanet2.EN_INITSETTING

_epanet2.EN_KBULK_swigconstant(_epanet2)
EN_KBULK = _epanet2.EN_KBULK

_epanet2.EN_KWALL_swigconstant(_epanet2)
EN_KWALL = _epanet2.EN_KWALL

_epanet2.EN_FLOW_swigconstant(_epanet2)
EN_FLOW = _epanet2.EN_FLOW

_epanet2.EN_VELOCITY_swigconstant(_epanet2)
EN_VELOCITY = _epanet2.EN_VELOCITY

_epanet2.EN_HEADLOSS_swigconstant(_epanet2)
EN_HEADLOSS = _epanet2.EN_HEADLOSS

_epanet2.EN_STATUS_swigconstant(_epanet2)
EN_STATUS = _epanet2.EN_STATUS

_epanet2.EN_SETTING_swigconstant(_epanet2)
EN_SETTING = _epanet2.EN_SETTING

_epanet2.EN_ENERGY_swigconstant(_epanet2)
EN_ENERGY = _epanet2.EN_ENERGY

_epanet2.EN_DURATION_swigconstant(_epanet2)
EN_DURATION = _epanet2.EN_DURATION

_epanet2.EN_HYDSTEP_swigconstant(_epanet2)
EN_HYDSTEP = _epanet2.EN_HYDSTEP

_epanet2.EN_QUALSTEP_swigconstant(_epanet2)
EN_QUALSTEP = _epanet2.EN_QUALSTEP

_epanet2.EN_PATTERNSTEP_swigconstant(_epanet2)
EN_PATTERNSTEP = _epanet2.EN_PATTERNSTEP

_epanet2.EN_PATTERNSTART_swigconstant(_epanet2)
EN_PATTERNSTART = _epanet2.EN_PATTERNSTART

_epanet2.EN_REPORTSTEP_swigconstant(_epanet2)
EN_REPORTSTEP = _epanet2.EN_REPORTSTEP

_epanet2.EN_REPORTSTART_swigconstant(_epanet2)
EN_REPORTSTART = _epanet2.EN_REPORTSTART

_epanet2.EN_RULESTEP_swigconstant(_epanet2)
EN_RULESTEP = _epanet2.EN_RULESTEP

_epanet2.EN_STATISTIC_swigconstant(_epanet2)
EN_STATISTIC = _epanet2.EN_STATISTIC

_epanet2.EN_PERIODS_swigconstant(_epanet2)
EN_PERIODS = _epanet2.EN_PERIODS

_epanet2.EN_NODECOUNT_swigconstant(_epanet2)
EN_NODECOUNT = _epanet2.EN_NODECOUNT

_epanet2.EN_TANKCOUNT_swigconstant(_epanet2)
EN_TANKCOUNT = _epanet2.EN_TANKCOUNT

_epanet2.EN_LINKCOUNT_swigconstant(_epanet2)
EN_LINKCOUNT = _epanet2.EN_LINKCOUNT

_epanet2.EN_PATCOUNT_swigconstant(_epanet2)
EN_PATCOUNT = _epanet2.EN_PATCOUNT

_epanet2.EN_CURVECOUNT_swigconstant(_epanet2)
EN_CURVECOUNT = _epanet2.EN_CURVECOUNT

_epanet2.EN_CONTROLCOUNT_swigconstant(_epanet2)
EN_CONTROLCOUNT = _epanet2.EN_CONTROLCOUNT

_epanet2.EN_JUNCTION_swigconstant(_epanet2)
EN_JUNCTION = _epanet2.EN_JUNCTION

_epanet2.EN_RESERVOIR_swigconstant(_epanet2)
EN_RESERVOIR = _epanet2.EN_RESERVOIR

_epanet2.EN_TANK_swigconstant(_epanet2)
EN_TANK = _epanet2.EN_TANK

_epanet2.EN_CVPIPE_swigconstant(_epanet2)
EN_CVPIPE = _epanet2.EN_CVPIPE

_epanet2.EN_PIPE_swigconstant(_epanet2)
EN_PIPE = _epanet2.EN_PIPE

_epanet2.EN_PUMP_swigconstant(_epanet2)
EN_PUMP = _epanet2.EN_PUMP

_epanet2.EN_PRV_swigconstant(_epanet2)
EN_PRV = _epanet2.EN_PRV

_epanet2.EN_PSV_swigconstant(_epanet2)
EN_PSV = _epanet2.EN_PSV

_epanet2.EN_PBV_swigconstant(_epanet2)
EN_PBV = _epanet2.EN_PBV

_epanet2.EN_FCV_swigconstant(_epanet2)
EN_FCV = _epanet2.EN_FCV

_epanet2.EN_TCV_swigconstant(_epanet2)
EN_TCV = _epanet2.EN_TCV

_epanet2.EN_GPV_swigconstant(_epanet2)
EN_GPV = _epanet2.EN_GPV

_epanet2.EN_NONE_swigconstant(_epanet2)
EN_NONE = _epanet2.EN_NONE

_epanet2.EN_CHEM_swigconstant(_epanet2)
EN_CHEM = _epanet2.EN_CHEM

_epanet2.EN_AGE_swigconstant(_epanet2)
EN_AGE = _epanet2.EN_AGE

_epanet2.EN_TRACE_swigconstant(_epanet2)
EN_TRACE = _epanet2.EN_TRACE

_epanet2.EN_CONCEN_swigconstant(_epanet2)
EN_CONCEN = _epanet2.EN_CONCEN

_epanet2.EN_MASS_swigconstant(_epanet2)
EN_MASS = _epanet2.EN_MASS

_epanet2.EN_SETPOINT_swigconstant(_epanet2)
EN_SETPOINT = _epanet2.EN_SETPOINT

_epanet2.EN_FLOWPACED_swigconstant(_epanet2)
EN_FLOWPACED = _epanet2.EN_FLOWPACED

_epanet2.EN_CFS_swigconstant(_epanet2)
EN_CFS = _epanet2.EN_CFS

_epanet2.EN_GPM_swigconstant(_epanet2)
EN_GPM = _epanet2.EN_GPM

_epanet2.EN_MGD_swigconstant(_epanet2)
EN_MGD = _epanet2.EN_MGD

_epanet2.EN_IMGD_swigconstant(_epanet2)
EN_IMGD = _epanet2.EN_IMGD

_epanet2.EN_AFD_swigconstant(_epanet2)
EN_AFD = _epanet2.EN_AFD

_epanet2.EN_LPS_swigconstant(_epanet2)
EN_LPS = _epanet2.EN_LPS

_epanet2.EN_LPM_swigconstant(_epanet2)
EN_LPM = _epanet2.EN_LPM

_epanet2.EN_MLD_swigconstant(_epanet2)
EN_MLD = _epanet2.EN_MLD

_epanet2.EN_CMH_swigconstant(_epanet2)
EN_CMH = _epanet2.EN_CMH

_epanet2.EN_CMD_swigconstant(_epanet2)
EN_CMD = _epanet2.EN_CMD

_epanet2.EN_TRIALS_swigconstant(_epanet2)
EN_TRIALS = _epanet2.EN_TRIALS

_epanet2.EN_ACCURACY_swigconstant(_epanet2)
EN_ACCURACY = _epanet2.EN_ACCURACY

_epanet2.EN_TOLERANCE_swigconstant(_epanet2)
EN_TOLERANCE = _epanet2.EN_TOLERANCE

_epanet2.EN_EMITEXPON_swigconstant(_epanet2)
EN_EMITEXPON = _epanet2.EN_EMITEXPON

_epanet2.EN_DEMANDMULT_swigconstant(_epanet2)
EN_DEMANDMULT = _epanet2.EN_DEMANDMULT

_epanet2.EN_LOWLEVEL_swigconstant(_epanet2)
EN_LOWLEVEL = _epanet2.EN_LOWLEVEL

_epanet2.EN_HILEVEL_swigconstant(_epanet2)
EN_HILEVEL = _epanet2.EN_HILEVEL

_epanet2.EN_TIMER_swigconstant(_epanet2)
EN_TIMER = _epanet2.EN_TIMER

_epanet2.EN_TIMEOFDAY_swigconstant(_epanet2)
EN_TIMEOFDAY = _epanet2.EN_TIMEOFDAY

_epanet2.EN_AVERAGE_swigconstant(_epanet2)
EN_AVERAGE = _epanet2.EN_AVERAGE

_epanet2.EN_MINIMUM_swigconstant(_epanet2)
EN_MINIMUM = _epanet2.EN_MINIMUM

_epanet2.EN_MAXIMUM_swigconstant(_epanet2)
EN_MAXIMUM = _epanet2.EN_MAXIMUM

_epanet2.EN_RANGE_swigconstant(_epanet2)
EN_RANGE = _epanet2.EN_RANGE

_epanet2.EN_MIX1_swigconstant(_epanet2)
EN_MIX1 = _epanet2.EN_MIX1

_epanet2.EN_MIX2_swigconstant(_epanet2)
EN_MIX2 = _epanet2.EN_MIX2

_epanet2.EN_FIFO_swigconstant(_epanet2)
EN_FIFO = _epanet2.EN_FIFO

_epanet2.EN_LIFO_swigconstant(_epanet2)
EN_LIFO = _epanet2.EN_LIFO

_epanet2.EN_NOSAVE_swigconstant(_epanet2)
EN_NOSAVE = _epanet2.EN_NOSAVE

_epanet2.EN_SAVE_swigconstant(_epanet2)
EN_SAVE = _epanet2.EN_SAVE

_epanet2.EN_INITFLOW_swigconstant(_epanet2)
EN_INITFLOW = _epanet2.EN_INITFLOW

def ENepanet(arg1, arg2, arg3, arg4):
    return _epanet2.ENepanet(arg1, arg2, arg3, arg4)
ENepanet = _epanet2.ENepanet

def ENopen(arg1, arg2, arg3):
    return _epanet2.ENopen(arg1, arg2, arg3)
ENopen = _epanet2.ENopen

def ENsaveinpfile(arg1):
    return _epanet2.ENsaveinpfile(arg1)
ENsaveinpfile = _epanet2.ENsaveinpfile

def ENclose():
    return _epanet2.ENclose()
ENclose = _epanet2.ENclose

def ENsolveH():
    return _epanet2.ENsolveH()
ENsolveH = _epanet2.ENsolveH

def ENsaveH():
    return _epanet2.ENsaveH()
ENsaveH = _epanet2.ENsaveH

def ENopenH():
    return _epanet2.ENopenH()
ENopenH = _epanet2.ENopenH

def ENinitH(arg1):
    return _epanet2.ENinitH(arg1)
ENinitH = _epanet2.ENinitH

def ENrunH():
    return _epanet2.ENrunH()
ENrunH = _epanet2.ENrunH

def ENnextH():
    return _epanet2.ENnextH()
ENnextH = _epanet2.ENnextH

def ENcloseH():
    return _epanet2.ENcloseH()
ENcloseH = _epanet2.ENcloseH

def ENsavehydfile(arg1):
    return _epanet2.ENsavehydfile(arg1)
ENsavehydfile = _epanet2.ENsavehydfile

def ENusehydfile(arg1):
    return _epanet2.ENusehydfile(arg1)
ENusehydfile = _epanet2.ENusehydfile

def ENsolveQ():
    return _epanet2.ENsolveQ()
ENsolveQ = _epanet2.ENsolveQ

def ENopenQ():
    return _epanet2.ENopenQ()
ENopenQ = _epanet2.ENopenQ

def ENinitQ(arg1):
    return _epanet2.ENinitQ(arg1)
ENinitQ = _epanet2.ENinitQ

def ENrunQ():
    return _epanet2.ENrunQ()
ENrunQ = _epanet2.ENrunQ

def ENnextQ():
    return _epanet2.ENnextQ()
ENnextQ = _epanet2.ENnextQ

def ENstepQ():
    return _epanet2.ENstepQ()
ENstepQ = _epanet2.ENstepQ

def ENcloseQ():
    return _epanet2.ENcloseQ()
ENcloseQ = _epanet2.ENcloseQ

def ENwriteline(arg1):
    return _epanet2.ENwriteline(arg1)
ENwriteline = _epanet2.ENwriteline

def ENreport():
    return _epanet2.ENreport()
ENreport = _epanet2.ENreport

def ENresetreport():
    return _epanet2.ENresetreport()
ENresetreport = _epanet2.ENresetreport

def ENsetreport(arg1):
    return _epanet2.ENsetreport(arg1)
ENsetreport = _epanet2.ENsetreport

def ENgetcontrol(arg1):
    return _epanet2.ENgetcontrol(arg1)
ENgetcontrol = _epanet2.ENgetcontrol

def ENgetcount(arg1):
    return _epanet2.ENgetcount(arg1)
ENgetcount = _epanet2.ENgetcount

def ENgetoption(arg1):
    return _epanet2.ENgetoption(arg1)
ENgetoption = _epanet2.ENgetoption

def ENgettimeparam(arg1):
    return _epanet2.ENgettimeparam(arg1)
ENgettimeparam = _epanet2.ENgettimeparam

def ENgetflowunits():
    return _epanet2.ENgetflowunits()
ENgetflowunits = _epanet2.ENgetflowunits

def ENgetpatternindex(arg1):
    return _epanet2.ENgetpatternindex(arg1)
ENgetpatternindex = _epanet2.ENgetpatternindex

def ENgetpatternid(arg1):
    return _epanet2.ENgetpatternid(arg1)
ENgetpatternid = _epanet2.ENgetpatternid

def ENgetpatternlen(arg1):
    return _epanet2.ENgetpatternlen(arg1)
ENgetpatternlen = _epanet2.ENgetpatternlen

def ENgetpatternvalue(arg1, arg2):
    return _epanet2.ENgetpatternvalue(arg1, arg2)
ENgetpatternvalue = _epanet2.ENgetpatternvalue

def ENgetqualtype():
    return _epanet2.ENgetqualtype()
ENgetqualtype = _epanet2.ENgetqualtype

def ENgeterror(arg1, arg3):
    return _epanet2.ENgeterror(arg1, arg3)
ENgeterror = _epanet2.ENgeterror

def ENgetnodeindex(arg1):
    return _epanet2.ENgetnodeindex(arg1)
ENgetnodeindex = _epanet2.ENgetnodeindex

def ENgetnodeid(arg1):
    return _epanet2.ENgetnodeid(arg1)
ENgetnodeid = _epanet2.ENgetnodeid

def ENgetnodetype(arg1):
    return _epanet2.ENgetnodetype(arg1)
ENgetnodetype = _epanet2.ENgetnodetype

def ENgetnodevalue(arg1, arg2):
    return _epanet2.ENgetnodevalue(arg1, arg2)
ENgetnodevalue = _epanet2.ENgetnodevalue

def ENgetlinkindex(arg1):
    return _epanet2.ENgetlinkindex(arg1)
ENgetlinkindex = _epanet2.ENgetlinkindex

def ENgetlinkid(arg1):
    return _epanet2.ENgetlinkid(arg1)
ENgetlinkid = _epanet2.ENgetlinkid

def ENgetlinktype(arg1):
    return _epanet2.ENgetlinktype(arg1)
ENgetlinktype = _epanet2.ENgetlinktype

def ENgetlinknodes(arg1):
    return _epanet2.ENgetlinknodes(arg1)
ENgetlinknodes = _epanet2.ENgetlinknodes

def ENgetlinkvalue(arg1, arg2):
    return _epanet2.ENgetlinkvalue(arg1, arg2)
ENgetlinkvalue = _epanet2.ENgetlinkvalue

def ENgetversion():
    return _epanet2.ENgetversion()
ENgetversion = _epanet2.ENgetversion

def ENsetcontrol(arg1, arg2, arg3, arg4, arg5, arg6):
    return _epanet2.ENsetcontrol(arg1, arg2, arg3, arg4, arg5, arg6)
ENsetcontrol = _epanet2.ENsetcontrol

def ENsetnodevalue(arg1, arg2, arg3):
    return _epanet2.ENsetnodevalue(arg1, arg2, arg3)
ENsetnodevalue = _epanet2.ENsetnodevalue

def ENsetlinkvalue(arg1, arg2, arg3):
    return _epanet2.ENsetlinkvalue(arg1, arg2, arg3)
ENsetlinkvalue = _epanet2.ENsetlinkvalue

def ENaddpattern(arg1):
    return _epanet2.ENaddpattern(arg1)
ENaddpattern = _epanet2.ENaddpattern

def ENsetpattern(arg1, floatarray):
    return _epanet2.ENsetpattern(arg1, floatarray)
ENsetpattern = _epanet2.ENsetpattern

def ENsetpatternvalue(arg1, arg2, arg3):
    return _epanet2.ENsetpatternvalue(arg1, arg2, arg3)
ENsetpatternvalue = _epanet2.ENsetpatternvalue

def ENsettimeparam(arg1, arg2):
    return _epanet2.ENsettimeparam(arg1, arg2)
ENsettimeparam = _epanet2.ENsettimeparam

def ENsetoption(arg1, arg2):
    return _epanet2.ENsetoption(arg1, arg2)
ENsetoption = _epanet2.ENsetoption

def ENsetstatusreport(arg1):
    return _epanet2.ENsetstatusreport(arg1)
ENsetstatusreport = _epanet2.ENsetstatusreport

def ENsetqualtype(arg1, arg2, arg3, arg4):
    return _epanet2.ENsetqualtype(arg1, arg2, arg3, arg4)
ENsetqualtype = _epanet2.ENsetqualtype
# This file is compatible with both classic and new-style classes.

cvar = _epanet2.cvar

